{"name": "test_register_failure_005", "status": "failed", "statusDetails": {"message": "AssertionError: 404 != 400", "trace": "self = <test_Newregister.TestNewregister testMethod=test_register_failure_005>\n\n      def test_register_failure_005(self):\n          response = requests.get('http://127.0.0.1:8000/home/ahttp://127.0.0.1:8000/home/api/register/pi/register/', params= { \"username\": \"userfour\",\n    \"email\": \"user.four@example.com\",\n    \"password\": \"anotherPass128\"})\n>         self.assertEqual(response.status_code, 400)\nE         AssertionError: 404 != 400\n\ntestplatform\\tests\\unit\\test_Newregister.py:48: AssertionError"}, "start": 1743341765200, "stop": 1743341765218, "uuid": "8b7a58dd-289e-41b2-932f-d43a5f4392e8", "historyId": "fa00da5eef7ecc5b711cdda0a4416d6f", "testCaseId": "fa00da5eef7ecc5b711cdda0a4416d6f", "fullName": "testplatform.tests.unit.test_Newregister.TestNewregister#test_register_failure_005", "labels": [{"name": "parentSuite", "value": "testplatform.tests.unit"}, {"name": "suite", "value": "test_Newregister"}, {"name": "subSuite", "value": "TestNewregister"}, {"name": "host", "value": "HO"}, {"name": "thread", "value": "17648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testplatform.tests.unit.test_Newregister"}]}