{"name": "test_login_sucess_001", "status": "failed", "statusDetails": {"message": "AssertionError: 405 != 200", "trace": "self = <test_Login.TestLogin testMethod=test_login_sucess_001>\n\n        def test_login_sucess_001(self):\n            response = requests.get('http://127.0.0.1:8000/home/api/login/', params={\n        \"username_or_email\": \"testuser\",\n        \"password\": \"testpassword\"\n    })\n>           self.assertEqual(response.status_code, 200)\nE           AssertionError: 405 != 200\n\ntestplatform\\tests\\unit\\test_Login.py:10: AssertionError"}, "start": 1743341765110, "stop": 1743341765116, "uuid": "97b65d1c-72f8-4683-a784-6bf9907114b4", "historyId": "9911482593c73b9ec5797f93f40bcf83", "testCaseId": "9911482593c73b9ec5797f93f40bcf83", "fullName": "testplatform.tests.unit.test_Login.TestLogin#test_login_sucess_001", "labels": [{"name": "parentSuite", "value": "testplatform.tests.unit"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "HO"}, {"name": "thread", "value": "17648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testplatform.tests.unit.test_Login"}]}