{"name": "test_register_failure_002", "status": "failed", "statusDetails": {"message": "AssertionError: 405 != 400", "trace": "self = <test_Newregister.TestNewregister testMethod=test_register_failure_002>\n\n      def test_register_failure_002(self):\n          response = requests.get('http://127.0.0.1:8000/home/api/register/', params= { \"username\": \"userfour\",\n    \"password\": \"anotherPass125\"})\n>         self.assertEqual(response.status_code, 400)\nE         AssertionError: 405 != 400\n\ntestplatform\\tests\\unit\\test_Newregister.py:28: AssertionError"}, "start": 1743386553009, "stop": 1743386553015, "uuid": "9e926f8b-f17a-4847-9f3a-de9fdb7b2b92", "historyId": "e29aa5c7dfdf2fb6a00055faf3ca8b11", "testCaseId": "e29aa5c7dfdf2fb6a00055faf3ca8b11", "fullName": "testplatform.tests.unit.test_Newregister.TestNewregister#test_register_failure_002", "labels": [{"name": "parentSuite", "value": "testplatform.tests.unit"}, {"name": "suite", "value": "test_Newregister"}, {"name": "subSuite", "value": "TestNewregister"}, {"name": "host", "value": "HO"}, {"name": "thread", "value": "22000-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testplatform.tests.unit.test_Newregister"}]}